// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace client
{
	public partial class AdminSearch : NSViewController
	{
		public String segueName;
		public String segueType;
		public String segueHours;
		public String segueLocation;
		public String segueAvailable = "";
		public String segueMaxNumber = "0";
		public AdminSearch (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			name.StringValue = segueName;
			type.StringValue = segueType;
			hours.StringValue = segueHours;
			location.StringValue = segueLocation;
			available.StringValue = segueAvailable;
			maxNumber.StringValue = segueMaxNumber;

		}
	}
}
