// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using client.ObjectHandler;
using core.Models;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace client
{
	public partial class LogIn : NSViewController, IMessageController
	{
        private BaseHandler baseHandler;
        
        public LogIn (IntPtr handle) : base (handle)
		{
			this.baseHandler = new BaseHandler(this);
		}

        public LogIn()
        {
            this.baseHandler = new BaseHandler(this);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
           // this.baseHandler = new BaseHandler(this);
        }
        partial void signIn_clicked(NSObject sender)
        {
			String userName = username.StringValue;
            String passWord = password.StringValue;

            if(userName.Trim().CompareTo("administrator") == 0)
            {
                this.View.Window.Close();
                BaseHandler.username = userName;
                var storyboard = NSStoryboard.FromName("Main", null);
                var controller = storyboard.InstantiateControllerWithIdentifier("AdministratorView") as NSWindowController;
                controller.ShowWindow(this);

            }
            else
            {
                baseHandler.logIn(userName, passWord);
            }     
        }

        partial void username_clicked(NSObject sender)
        {
            messageLog.StringValue = "";
            
        }

        partial void password_clicked(NSObject sender)
        {
            messageLog.StringValue = "";
        }

        public  void showMessage(String message)
        {
            this.InvokeOnMainThread(() => { messageLog.StringValue = message; });
        }

        public void openWindow()
        {
            this.InvokeOnMainThread(() => {
                
                this.View.Window.Close();
                BaseHandler.username = username.StringValue;
                var storyboard = NSStoryboard.FromName("Main", null);
                var controller = storyboard.InstantiateControllerWithIdentifier("UserView") as NSWindowController;
                controller.ShowWindow(this);
            });
        }

        public void showActivity(Activity activity)
        {
            
        }

        public void showList(List<Activity> activites)
        {
            
        }

        public void showUser(User user)
        {
            
        }

        public void showAlert()
        {
            throw new NotImplementedException();
        }
    }
}