// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using client.ObjectHandler;
using core.Models;
using System.Collections.Generic;
using System.Threading;

namespace client
{
	public partial class Register : NSViewController, IMessageController
	{
      
        private UserHandler userHandler;
        public static bool didGoBack = false;
		public Register (IntPtr handle) : base (handle)
		{
          
            this.userHandler = new UserHandler(this);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
          
            userHandler = new UserHandler(this);
            String activityName = BaseHandler.activityName;
            userHandler.handleActivitiesName(activityName);
        
        }

        public void openWindow()
        {
           
        }

        public void showActivity(Activity activity)
        {
            InvokeOnMainThread(() => {rate.StringValue = activity.rate.ToString(); });
        }

        public void showList(List<Activity> activites)
        {
            
        }

        public void showMessage(string message)
        {
            this.InvokeOnMainThread(() => { messageLog.StringValue = message; });
        }

        public void showUser(User user)
        {
            
        }

      
        partial void back(NSObject sender)
        {
            this.View.Window.Close();
            didGoBack = true;
        }

        partial void register_clicked(NSObject sender)
        {
            String activityName = BaseHandler.activityName;
            String username = BaseHandler.username;
            String number = numberOfPeople.StringValue;
            String ratingNumber = rate.StringValue;
            Console.WriteLine(ratingNumber);
            if (number.CompareTo("") == 0)
            {
                number = "0";
                messageLog.StringValue = "\t    Activity succesfully rated!";
                userHandler.updateRating(activityName, ratingNumber);
            }
            else
            {
                userHandler.register(number, username, activityName, ratingNumber);
            }
          
        }

        public void showAlert()
        {
            
        }
    }
}
