// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace client
{
	public partial class SearchActivities : NSViewController
	{
		public String segueList = "";
		public SearchActivities (IntPtr handle) : base (handle)
		{
			this.segueList = "";
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			content.StringValue = "";
			content.StringValue = segueList;
		}
	}
}
