// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace client
{
	public partial class SearchUser : NSViewController
	{
        public String segueFName;
        public String segueLName;
        public String segueCountry;
        public String segueAddress;
        public String segueCity;
        public String segueState;
        public SearchUser (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            firstName.StringValue = segueFName;
            lastName.StringValue = segueLName;
            country.StringValue = segueCountry;
            city.StringValue = segueCity;
            state.StringValue = segueState;
            address.StringValue = segueAddress;
        }
    }
}
