// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace client
{
	public partial class UserSearch : NSViewController
	{
		public String segueName;
		public String segueType;
		public String segueHours;
		public String segueLocation;
      
		public UserSearch (IntPtr handle) : base (handle)
		{
            
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            name.StringValue = segueName;
            type.StringValue = segueType;
            hours.StringValue = segueHours;
            location.StringValue = segueLocation;

        }
    }
}
