// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace client
{
	public partial class CreateAccountWindow : NSWindow
	{
		public CreateAccountWindow (IntPtr handle) : base (handle)
		{
		}
	}
}
